### ISSUE TITLE
docs issue?

### ISSUE THREAD

**Issue by gregveres** [vuejs/eslint-config-typescript#10]
When I read the Readme.MD file for this project, I get confused because the readme says that it provides 2 rulesets: @vue/eslint-config-typescript and @vue/eslint-config-typescript/recommended but then it goes on to say here are some sample .eslintrc.js files but neither of the examples include these two rulesets. 

Shouldn't the docs show how to use the rulesets? Or if @vue/typescript somehow includes @vue/eslint-config-typescript, than that should be explicitly called out.

**Comment by sodatea** [comment]
`@vue/typescript` and `@vue/eslint-config-typescript` are equivalent.

https://eslint.org/docs/user-guide/configuring#using-a-shareable-configuration-package
> The `extends` property value can omit the `eslint-config-` prefix of the package name.
