### ISSUE TITLE
Issues with peer dependencies found

### ISSUE THREAD

**Issue by Valexr** [vuejs/eslint-config-typescript#101]
packages/vue
├─┬ @typescript-eslint/parser 6.21.0
│ └── ✕ unmet peer eslint@"^7.0.0 || ^8.0.0": found 9.14.0
└─┬ @vue/eslint-config-typescript 12.0.0
  ├── ✕ unmet peer eslint@"^6.2.0 || ^7.0.0 || ^8.0.0": found 9.14.0
  └─┬ @typescript-eslint/eslint-plugin 6.21.0
    ├── ✕ unmet peer eslint@"^7.0.0 || ^8.0.0": found 9.14.0
    ├─┬ @typescript-eslint/utils 6.21.0
    │ └── ✕ unmet peer eslint@"^7.0.0 || ^8.0.0": found 9.14.0
    └─┬ @typescript-eslint/type-utils 6.21.0
      └── ✕ unmet peer eslint@"^7.0.0 || ^8.0.0": found 9.14.0

**Comment by haoqunjiang** [comment]
You might be using an old version of this package. It's updated in the latest release.
