### ISSUE TITLE
Update typescript-eslint to version 8.15.0 : "TypeError: Error while loading rule @typescript-eslint"

### ISSUE THREAD

**Issue by messenjer** [vuejs/eslint-config-typescript#104]
When I update eslint to version 9.15.0, `npm run lint` failed

> Oops! Something went wrong! :(
> 
> ESLint: 9.15.0
> 
> TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
> 

Issue here : 
* https://github.com/typescript-eslint/typescript-eslint/issues/10353
* New release here: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.15.0 

Mentioned here also : 
* https://github.com/vuejs/eslint-config-typescript/pull/103

**Comment by haoqunjiang** [comment]
Fixed in the latest release.
