### ISSUE TITLE
Update to @typescript-eslint/* v3

### ISSUE THREAD

**Issue by sodatea** [vuejs/eslint-config-typescript#11]
Here's the changelog: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0

Need to introduce some breaking changes to this package.

**Comment by vadimyen** [comment]
It would be great!

**Comment by bodograumann** [comment]
Maybe we should imediately move to v4: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.0.0-rc

**Comment by gintsmurans** [comment]
Came here to create and issue, that @typescript-eslint/parser@^2.7.0 recommends eslint@^5.0.0 || ^6.0.0 but I guess jumping to v3 would solve it.

**Comment by Mister-Hope** [comment]
> Maybe we should imediately move to v4: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.0.0-rc

Totallty agreed, two major is left behind.

**Comment by Mister-Hope** [comment]
Any idea to support V4?@sodatea

**Comment by sodatea** [comment]
Working on it. Maybe tomorrow 🙂
