### ISSUE TITLE
npm install and npx install-peerdeps throws Error

### ISSUE THREAD

**Issue by Who-Code** [vuejs/eslint-config-typescript#13]
Hi Folks,
since today our Pipeline failed.

After further investigation we found the possible issue:
npm install for @vue/eslint-config-typescript fails with Error 404

Also we tried npx install-peerdeps --dev @vue/eslint-config-typescript and this also crashes.

Here is the Part of our package.json:

```
"devDependencies": {
       ........
        "@vue/eslint-config-typescript": "^5.0.1",
       ........
```

Here is the process when trying to manually install:

```
$: npm install @vue/eslint-config-typescript

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vue%2feslint-config-typescript - Not found
npm ERR! 404 
npm ERR! 404  '@vue/eslint-config-typescript@^5.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/robertkeller/.npm/_logs/2020-08-06T11_04_50_532Z-debug.log
```

And here the npx peerdeps:

```
$: npx install-peerdeps --dev @vue/eslint-config-typescript

install-peerdeps v2.0.3
ERR That package doesn't exist. Did you mean to specify a custom registry?
```

We are using the standard npm registry.

Thanks for your help.

**Comment by sodatea** [comment]
https://status.npmjs.org/incidents/cksjqc1w11v5
Sorry, I forgot to respond to this issue, but it was an npm registry issue and has been resolved since.
