### ISSUE TITLE
Annotating Props typescript

### ISSUE THREAD

**Issue by victororlyk** [vuejs/eslint-config-typescript#22]
Annotating Props with typescript shows strange eslint error. 
My setup is nuxtjs with composition api
.eslintrc.json
```
{
  "root": true,
  "env": {
    "browser": true,
    "node": true
  },
  "parserOptions": {
    "parser": "babel-eslint"
  },
  "extends": [
    "@nuxtjs/eslint-config-typescript",
    "prettier",
    "plugin:nuxt/recommended",
    "@vue/typescript/recommended",
    "plugin:cypress/recommended",

    "plugin:prettier/recommended",
    "prettier/vue"
  ],
  "plugins": ["prettier"],
  // add your custom rules here
  "rules": {
    "semi": [2, "always"]
  }
}

```
<img width="696" alt="Screenshot 2021-04-30 at 09 22 19" src="https://user-images.githubusercontent.com/33072590/116658307-6e903600-a998-11eb-80a9-768a06983a20.png">
<img width="641" alt="Screenshot 2021-04-30 at 09 56 16" src="https://user-images.githubusercontent.com/33072590/116659478-56b9b180-a99a-11eb-820e-d81e754d9c59.png">

**Comment by danielroe** [comment]
@victororlyk The issue is likely the fact that you are using `babel-eslint` as your parser (which doesn't understand TypeScript). You should either switch to https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser or https://www.npmjs.com/package/@babel/eslint-parser.
