### ISSUE TITLE
How does @vue/typescript/recommended  correspond to this project

### ISSUE THREAD

**Issue by social-uni** [vuejs/eslint-config-typescript#27]
chinese:

我想要知道@vue/typescript/recommended中有哪些规则，所以我想要找到@vue/typescript/recommended对应的项目，但是我并没有在
/node_modules/@vue中发现 @vue/typescript , 然后我通过搜索引擎，大概了解到@vue/typescript/recommended 对应 vue/eslint-config-typescript，但是我不明白，他们是如何工作的，是如何对应的

english:

I want to know what rules are in @vue/typescript/recommended, so I want to find the corresponding project @vue/typescript/recommended, but I am not in
I found @vue/typescript in /node_modules/@vue, and then through search engines, I probably learned that @vue/typescript/recommended corresponds to vue/eslint-config-typescript, but I don’t understand how they work and how they correspond of

**Comment by social-uni** [comment]
![image](https://user-images.githubusercontent.com/14007972/121657726-3c174400-cad3-11eb-88ab-1a67db0b8844.png)

I feel that it does not meet the eslint specification

**Comment by social-uni** [comment]
找到了类似问题 https://github.com/vuejs/eslint-config-typescript/issues/10

**Comment by zhang-glitch** [comment]
对，我也想知道，'@vue/typescript/recommended'内部到底设置了哪些配置
