### ISSUE TITLE
Support for `recommended-requiring-type-checking` and `all`

### ISSUE THREAD

**Issue by rafaellehmkuhl** [vuejs/eslint-config-typescript#29]
Are there plans to support the [`recommended-requiring-type-checking`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/src/configs#recommended-requiring-type-checking) and the [`all`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/src/configs#all) sets from typescript-eslint?
Would a PR for that be welcome?

**Comment by segevfiner** [comment]
Will need https://github.com/vuejs/vue-eslint-parser/issues/104

**Comment by n0099** [comment]
```json
parser: 'vue-eslint-parser',
parserOptions: {
    parser: '@typescript-eslint/parser',
    project: ['./tsconfig.json', './tsconfig.node.json'],
    tsconfigRootDir: __dirname,
},
```

**Comment by haoqunjiang** [comment]
Supported in v14.
