### ISSUE TITLE
Available rules link leads to Page Not Found

### ISSUE THREAD

**Issue by andrewalc** [vuejs/eslint-config-typescript#38]
The README begins with:
See [@typescript-eslint/eslint-plugin](https://typescript-eslint.io/eslint-plugin) for available rules.

But leads to this page:
![image](https://user-images.githubusercontent.com/22480139/145247538-75dab7fd-00df-4fe5-bdb5-0412859d7ac1.png)

Is this link still active somewhere else? I can't seem to find where this was supposed to lead.

**Comment by sodatea** [comment]
Thanks for reporting! It's supposed to link to this page: https://typescript-eslint.io/rules/
