### ISSUE TITLE
Imported modules only used as type annotation are marked as `no-unused-vars`

### ISSUE THREAD

**Issue by doits** [vuejs/eslint-config-typescript#5]
Thanks for the latest update to v5! If just tried it out and it works fine, though I know have another problem which I don't exactly know if `estlint-config-typescript` introduced it or something else ...

My config looks like this:

```json
    "extends": [
      "eslint:recommended",
      "plugin:vue/recommended",
      "plugin:jest/recommended",
      "@vue/eslint-config-typescript",
      "@vue/eslint-config-prettier"
    ],
```

Now in my .vue files if I do this, I get a `no-unused-vars` error:

```js
...
import { Location } from "vue-router/types"

export default Vue.extend({
  ...
  methods: {
    getLocation(): Location {
      return { name: "some_location" }
    }
  }
})

// => no-unused-vars: 'Location' is defined but never used
```

The key points are:

- `Location` is only imported because it is used as a *type annotation*
- `Location` is never explicitly used but as the return type of the method
- Other imports work fine which are used inside methods or computed getters beside type annotation

I didn't have this before upgrading to v5, but a lot of things changed during that upgrade (new peer dependencies, other packages upgraded) so I'm sorry if this is the wrong place to report  it.

Is this something that can be fixed here or elsewhere?

**Comment by doits** [comment]
Allright, sorry, fixed it with this:

```js
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/eslint-recommended",
      "plugin:@typescript-eslint/recommended",
      "plugin:vue/recommended",
      "plugin:jest/recommended",
      "@vue/eslint-config-typescript",
      "@vue/eslint-config-prettier"
    ],
```

Looks like I was missing the `plugin:@typescript-eslint/recommended` part, see https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin

**Comment by sodatea** [comment]
You can use the recommended set from this package, too, so that you won't need to manually add `plugin:@typescript-eslint/eslint-recommended` and `plugin:@typescripteslint/recommended`.

See https://github.com/vuejs/eslint-config-typescript#vueeslint-config-typescriptrecommended

**Comment by Naartti** [comment]
I had this problem when starting a new project with vue-cli (4.2.0) and had to change eslintrc to:
```js
extends: [
    'standard',
    'plugin:vue/essential',
    'plugin:vue/typescript',
]
```

**Comment by Naartti** [comment]
Had the same issue when starting a new project with vue cli (4.2.0) (with standard eslint-rules) and had to change ```.eslintrc``` to:
```js
extends: [
    'standard',
    'plugin:vue/essential',
    '@vue/typescript',
    '@vue/standard',
    '@vue/typescript/recommended',
    '@vue/eslint-config-typescript',
  ]
```
