### ISSUE TITLE
typescript-eslint@v6

### ISSUE THREAD

**Issue by kachkaev** [vuejs/eslint-config-typescript#57]
Announcement: https://typescript-eslint.io/blog/announcing-typescript-eslint-v6

It’d be great to discuss the timeline for a downstream update as well as potential caveats.

**Comment by fdc-viktor-luft** [comment]
Please also consider this: https://github.com/vuejs/eslint-config-typescript/issues/59

**Comment by TheSeg** [comment]
Checking in on the status of this issue and project.

ESLint Typescript is currently at [v6.5.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v6.5.0), where as the working version of ESLint for this project is [v5.62.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.62.0).
