### ISSUE TITLE
[Feature request] Support typescript-eslint v7

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/eslint-config-typescript#69]
Support typescript-eslint v7

**Comment by TheSeg** [comment]
More notes about [ESLint v7](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7/). To quote the breaking changes:

1. Update Node.js engine requirement to `^18.18.0 || >=20.0.0`. This means we are dropping support for Node 16, 19, and Node 18 versions prior to 18.18.0. Note that this is the same requirement that ESLint v9 will impose.
2. Update the TypeScript peer dependency requirement to `>=4.7.4`.
3. Update the ESLint peer dependency requirement to `^8.56.0`.

**Comment by Oscaner** [comment]
Hi, any updates?
