### ISSUE TITLE
using recommended order, not getting correct results

### ISSUE THREAD

**Issue by xerosanyam** [vuejs/eslint-config-typescript#7]
order of plugins mentioned in README.md is
```
'extends': [
    'plugin:vue/essential',
    '@vue/standard',
    '@vue/typescript'
  ]
```
however, I don't get `eslint(no-unused-vars)` errors for this config.
works fine with this order
```
'extends': [
    '@vue/typescript',
    '@vue/standard',
 'plugin:vue/essential'
  ],
```

**Comment by sodatea** [comment]
See the comments here:
https://github.com/vuejs/eslint-config-typescript/blob/166bc0de599f03435dca7fa4af8589d9b259bed5/index.js#L20-L22

You'll have to manually enable the `@typescript-eslint/no-unused-vars` rule.
Or you can use the `@vue/typescript/recommended` ruleset, which has already done this internally, along with enabling other type-related rules.
