### ISSUE TITLE
Flat config support

### ISSUE THREAD

**Issue by rijenkii** [vuejs/eslint-config-typescript#72]
I see that it has been mentioned a couple of times (https://github.com/vuejs/eslint-config-typescript/issues/59#issuecomment-1718922854, https://github.com/vuejs/eslint-config-typescript/pull/48#issuecomment-1527163212), it is still not supported.

**Comment by rijenkii** [comment]
Bump, now that `eslint-plugin-vue` supports flat configs: https://github.com/vuejs/eslint-plugin-vue/releases/tag/v9.24.0.

**Comment by mwkcoding** [comment]
This should happen ASAP as the eslintrc config is deprecated.

**Comment by bmulholland** [comment]
Flat Config solves [the ESLint sub-dependency limitation noted in the README](https://github.com/vuejs/eslint-config-typescript?tab=readme-ov-file#installation), so that section should be updated when the plugin is.
