### ISSUE TITLE
Support ESLint `v9`

### ISSUE THREAD

**Issue by simensol** [vuejs/eslint-config-typescript#76]
Just a heads up, ESLint `v9` was released recently and it seems to be incompatible with `@vue/eslint-config-typescript`. Here's the error I got:

```bash
npm ERR! ERESOLVE could not resolve
npm ERR! While resolving: @vue/eslint-config-typescript@13.0.0
npm ERR! Found: eslint@9.0.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.0.0" from the root project
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^8.56.0" from @vue/eslint-config-typescript@13.0.0
npm ERR! node_modules/@vue/eslint-config-typescript
npm ERR!   dev @vue/eslint-config-typescript@"^13.0.0" from the root project
npm ERR! Conflicting peer dependency: eslint@8.57.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^8.56.0" from @vue/eslint-config-typescript@13.0.0
npm ERR!   node_modules/@vue/eslint-config-typescript
npm ERR!     dev @vue/eslint-config-typescript@"^13.0.0" from the root project
```

**Comment by lvzhenbo** [comment]
Wait for the maintainer to update it, eslint 9.0 made a lot of destructive changes, including configuration files 
See this blog for details https://eslint.org/docs/latest/use/migrate-to-9.0.0

**Comment by JoostKersjes** [comment]
I've been working on https://github.com/vuejs/create-eslint-config/pull/25

That helped me understand a bit of what is possible with ESLint v9, so I tried it just now on one of my projects.

When I use `...compat.extends("@vue/eslint-config-typescript")`, it throws up a bunch of parsing errors:
- `error  Parsing error: Unexpected token <`
- `error  Parsing error: Unexpected token :`
- `error  Parsing error: Unexpected token type`

But for some reason that doesn't happen with `...compat.extends("@vue/eslint-config-typescript/recommended")`.

Here is the full config that works for me with ESLint 9, Vue 3, TypeScript & Prettier:

```
// eslint.config.js
import path from "node:path";
import { fileURLToPath } from "node:url";

import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import pluginVue from "eslint-plugin-vue";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
});

export default [
  js.configs.recommended,
  ...pluginVue.configs["flat/essential"],
  ...compat.extends("@vue/eslint-config-typescript/recommended"),
  ...compat.extends("@vue/eslint-config-prettier/skip-formatting"),
  {
    files: [
      "**/*.vue",
      "**/*.js",
      "**/*.jsx",
      "**/*.cjs",
      "**/*.mjs",
      "**/*.ts",
      "**/*.tsx",
      "**/*.cts",
      "**/*.mts",
    ],
    languageOptions: {
      ecmaVersion: "latest",
    },
  },
];
```

**Comment by susnux** [comment]
This depends on typescript-eslint to provide v9 support first, ref: https://github.com/typescript-eslint/typescript-eslint/issues/8211

**Comment by riodw** [comment]
## Full thread for SEO:

```shell
% npm i

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: doormatkey.vue@0.1.0
npm ERR! Found: eslint@9.2.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"9.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^8.56.0" from @vue/eslint-config-typescript@13.0.0
npm ERR! node_modules/@vue/eslint-config-typescript
npm ERR!   dev @vue/eslint-config-typescript@"13.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by grindpride** [comment]
wait for support

**Comment by cweijan** [comment]
I am upgrading eslint v9. After referring to eslint-config-typescript, I found that it is easy to add a new eslint v9 rule to support.
```js
{
        files: ["**/*.vue"],
        languageOptions: {
            parserOptions: {
                parser: {
                    'js': 'espree',
                    'jsx': 'espree',
                    'mjs': 'espree',
                    'ts': tseslint.parser,
                    'tsx': tseslint.parser,
                    'mts': tseslint.parser,
                    // Leave the template parser unspecified, so that it could be determined by `<script lang="...">`
                },
                extraFileExtensions: ['.vue'],
                ecmaFeatures: {
                    jsx: true
                }
            }
        }
}
```
![image](https://github.com/vuejs/eslint-config-typescript/assets/27798227/92a985b9-6909-42a5-94ce-42b51ef89538)

**Comment by rijenkii** [comment]
Here's the config that I've just wrote. Haven't tested much, but it seems to work:
```javascript
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginVue from "eslint-plugin-vue";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs["flat/recommended"],
  {
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
        projectService: true,
        extraFileExtensions: ['.vue'],
      },
    },
  },
);
```

`tseslint.configs.*TypeChecked` configs also work, but there are issues, see https://github.com/vuejs/vue-eslint-parser/issues/104.

Also, when using `*TypeChecked` configs be sure to add `{ "ignore": ["eslint.config.js"] }` to your configs, as `eslint-plugin-vue` is not typed (https://github.com/vuejs/eslint-plugin-vue/issues/2124).

**Comment by lovetingyuan** [comment]
@sodatea  hi, please check out this, It has been a while time after eslint v9 released.

**Comment by Shyam-Chen** [comment]
I have integrated TypeScript, Vue, and Prettier in ESLint v9, and it is working well. Just sharing for everyone's reference.

`eslint.config.js`: https://github.com/Shyam-Chen/Vue-Starter/blob/main/eslint.config.js

**Comment by Gnuk** [comment]
I've just done #79 PR few days ago, maybe someone of you want to review this draft (I have one issue remaining).

**Comment by MartinX3** [comment]
Nice @Gnuk   
With the new ESlint 9.9.0 and the needed feature flag you could also use eslint.config.ts.

**Comment by Evgenios95** [comment]
Feel free to delete this comment if not relevant, but I am still getting issues in the console when I am trying to bump `ESLint` from `8.57.0 `to `9+`.

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @vue/eslint-config-typescript@13.0.0
npm error Found: eslint@9.9.0
npm error node_modules/eslint
npm error   dev eslint@"^9.9.0" from the root project
npm error   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
...
npm error peer eslint@"^8.56.0" from @vue/eslint-config-typescript@13.0.0
npm error node_modules/@vue/eslint-config-typescript
npm error   dev @vue/eslint-config-typescript@"^13.0.0" from the root project
```

I guess it is not done/ supported yet?

**Comment by throrin19** [comment]
Any news about that ?

**Comment by bmulholland** [comment]
v8 is EOL in a month: https://eslint.org/version-support/

**Comment by orimay** [comment]
> When using flat config, packages `@typescript-eslint/{parser,eslint-plugin}` should be replaced by the merged [`typescript-eslint`](https://www.npmjs.com/package/typescript-eslint/) since they only provide flat `.configs` in that package: [typescript-eslint/typescript-eslint#7935](https://github.com/typescript-eslint/typescript-eslint/pull/7935)
> 
> But if you have both `@typescript-eslint/{parser,eslint-plugin}` and `typescript-eslint` installed and applying [#76 (comment)](https://github.com/vuejs/eslint-config-typescript/issues/76#issuecomment-2051234597):
> 
> ```js
> import vueESLintConfigTypescriptRecommendedExtends from '@vue/eslint-config-typescript/recommended.js'
> import typescriptESLint from 'typescript-eslint';
> 
> export default [
>     ...compat.config(vueESLintConfigTypescriptRecommendedExtends), // same with ...compat.extends('@vue/eslint-config-typescript/recommended')
>     ...typescriptESLint.configs.strictTypeChecked,
>     ...typescriptESLint.configs.stylisticTypeChecked,
> ];
> ```
> 
> they won't work together:
> 
> ```js
> ConfigError: Config "typescript-eslint/base": Key "plugins": Cannot redefine plugin "@typescript-eslint".
> ```

I handled it like this:
```ts
function dedulplicatePlugins(
  ...plugins: TSESLint.FlatConfig.ConfigArray
): TSESLint.FlatConfig.ConfigArray {
  const foundPlugins = new Set<string>();
  return plugins.filter(plugin => {
    if (plugin.name === undefined) return true;
    if (foundPlugins.has(plugin.name)) return false;
    foundPlugins.add(plugin.name);
    if (plugin.name === 'typescript-eslint/base') {
      delete plugin.plugins?.['@typescript-eslint'];
    }
    return true;
  });
}



const eslintConfig: ReturnType<typeof tsESLint.config> = tsESLint.config(
  js.configs.recommended,
  ...dedulplicatePlugins(
    ...tsESLint.configs.strict,
    ...tsESLint.configs.stylistic,
  ),
  // ..
```

**Comment by NathanAP** [comment]
We really need an update on this issue.
Why is it closed in first place?

**Comment by mitar** [comment]
I think it should work since version v14? Which version are you using?

**Comment by NathanAP** [comment]
Huh I guess I messed up on the first warning I got. Probably a cache while updating. Recreating my `package-lock.json` fixed the warning.

Sorry! I'll mark everything as not relevant.
