### ISSUE TITLE
[14.0.0-rc0] very slow compared to v13

### ISSUE THREAD

**Issue by chrisnruud** [vuejs/eslint-config-typescript#82]
Hello. We are in the early proess of migrating our common eslint libraries to eslint 9 and when using the rc - version of v14 to consolidate our config, it _works_ like expected, but the execution is several magnitudes slower than the same configuration on v13 / eslint 8 - unless we are doing something wrong in our implementation (just a bare - bones configuration setup is significantly slower) - then we hope that we can be able to either debug or that this is fixed in the release :)

https://github.com/dsb-norge/eslint-config-dsb-vue3-ts/tree/eslint9 for reference

**Comment by haoqunjiang** [comment]
Would you happen to have an example project for me to benchmark?

One possible problem is that I missed a performance tweak that could improve the parsing speed of SFCs with no `<script>` blocks. It's fixed in 14.0.0-rc.1. Could you check it out and see if the fix works?

**Comment by chrisnruud** [comment]
Hi and thanks for the reply. All of our lager projects are not open source so I cannot share their code, I can probably get eslint --debug logs for runs using the eslint 8 and eslint 9 implementations , if not, I'll see what I can do to fork some of the internal code and clean it up for debug purposes

**Comment by chrisnruud** [comment]
I have released a pre-release of our shared config over at https://www.npmjs.com/package/@dsb-norge/eslint-config-dsb-vue3-ts as well

**Comment by chrisnruud** [comment]
added debug for `main.ts` and `[vite.config.ts]` using the commands
[main.ts.debug.txt](https://github.com/user-attachments/files/17253881/main.ts.debug.txt)
[vite.config.ts.debug.txt](https://github.com/user-attachments/files/17253882/vite.config.ts.debug.txt)

`DEBUG=typescript-eslint:* npx eslint ./vite.config.ts`  and `DEBUG=typescript-eslint:* npx eslint ./src/main.ts`

**Comment by haoqunjiang** [comment]
Thanks for the debug log!
I found that I accidentally enabled `projectService` by default for all Vue files ([should be off by default](https://typescript-eslint.io/packages/parser#projectservice)) 😅 And that incorrect configuration spread to normal `.ts` files due to the abovementioned `.map` call.
So typescript-eslint was trying to get the type info of all the files, significantly slowing down the whole process…

It's fixed in `14.0.0-rc.2`. Could you try it out?

**Comment by robtesch** [comment]
@haoqunjiang I was also having issues with `14.0.0-rc.0` and `14.0.0-rc.1` being incredibly slow on my project (5 - 10 min vs 10 - 30 sec on eslint 8). I've just tried `14.0.0-rc.2` and it's much much faster. I haven't done the detailed testing to check if it's as fast as 13.x with eslint 8, but it's definitely useable again. Thanks!

**Comment by chrisnruud** [comment]
Building our sharable config using rc2 is significantly faster than rc0 through 1 👍 I cannot say if it is _as_fast as using v13, but its definitely usable on even our largest application as - is!
