### ISSUE TITLE
Rules ignored with eslint 9

### ISSUE THREAD

**Issue by DavidVaness** [vuejs/eslint-config-typescript#88]
Hey guys, maybe I am lost in the migration, but I am unable to toggle off / change any eslint rules. 

```ts
[
  {
    ignores: ['dist/**'],
  },
  ...pluginVue.configs['flat/recommended'],
  ...vueTsEslintConfig(),
    {
      files: ["**/*.{.vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts}"],
      rules: {
       'no-unused-vars': 'off',
        "@typescript-eslint/no-unused-vars": 'off',
  }
]
```

@typescript-eslint/no-unused-vars still errors

"@vue/eslint-config-typescript": "14.0.0"
"eslint-plugin-vue": "9.28.0",

**Comment by haoqunjiang** [comment]
`*.{.vue`

Extraneous dot.

**Comment by DavidVaness** [comment]
> `*.{.vue`
> 
> Extraneous dot.

Thank you sir, apparently I dropped my glasses somewhere
